#!/usr/bin/env node

/**
 * Setup .env.local file with Supabase credentials
 * This script helps you configure your environment variables
 */

require('dotenv').config({ path: '.env.local' });
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function main() {
  console.log('🔧 Supabase Environment Setup\n');
  console.log('This script will help you set up your .env.local file.\n');
  console.log('📋 You need to get these from Supabase Dashboard:\n');
  console.log('   1. Go to: Settings > API');
  console.log('      - Copy: Project URL');
  console.log('      - Copy: anon public key');
  console.log('      - Copy: service_role key');
  console.log('');
  console.log('   2. Go to: Settings > Database > Connect');
  console.log('      - Select "Connection pooling" tab');
  console.log('      - Copy connection string');
  console.log('      - Replace [YOUR-PASSWORD] with your database password');
  console.log('      - URL-encode special chars (@ → %40)\n');

  // Detect project ID from URL if already set
  const currentUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  let projectId = null;
  
  if (currentUrl) {
    const match = currentUrl.match(/https:\/\/([^.]+)\.supabase\.co/);
    if (match) {
      projectId = match[1];
      console.log(`📌 Detected project ID: ${projectId}\n`);
    }
  }

  // Get credentials
  const supabaseUrl = await question(`Supabase Project URL${currentUrl ? ` (current: ${currentUrl})` : ''}: `) || currentUrl || '';
  const supabaseAnonKey = await question(`Supabase Anon Key${process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ? ' (press Enter to keep current)' : ''}: `) || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
  const supabaseServiceKey = await question(`Supabase Service Role Key${process.env.SUPABASE_SERVICE_ROLE_KEY ? ' (press Enter to keep current)' : ''}: `) || process.env.SUPABASE_SERVICE_ROLE_KEY || '';
  const databaseUrl = await question(`Database URL (Connection String)${process.env.DATABASE_URL ? ' (press Enter to keep current)' : ''}: `) || process.env.DATABASE_URL || '';

  if (!supabaseUrl || !supabaseAnonKey || !supabaseServiceKey || !databaseUrl) {
    console.error('\n❌ All fields are required!');
    console.error('Please run this script again and provide all values.\n');
    rl.close();
    process.exit(1);
  }

  // Create .env.local content
  const envContent = `# Supabase Configuration
# Generated by setup-env.js

# Supabase Auth
NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnonKey}
SUPABASE_SERVICE_ROLE_KEY=${supabaseServiceKey}

# Database Connection
DATABASE_URL=${databaseUrl}
`;

  // Write to file
  const envPath = path.join(__dirname, '.env.local');
  fs.writeFileSync(envPath, envContent);

  console.log('\n✅ .env.local file created/updated successfully!\n');
  console.log('📁 Location:', envPath);
  console.log('\n📝 Next steps:');
  console.log('   1. Run the SQL migration in Supabase SQL Editor');
  console.log('   2. Create admin user via Supabase Dashboard');
  console.log('   3. Start the admin panel: npm run dev\n');

  rl.close();
}

main().catch(error => {
  console.error('\n❌ Error:', error.message);
  rl.close();
  process.exit(1);
});



